# https://travis-ci.org

language: c
os: osx
osx_image: xcode11.3

before_install:
  - brew update
  - brew install ldid dpkg xz
  - export THEOS=/opt/theos
  - git clone --recursive https://github.com/theos/theos.git $THEOS

script:
  - make package
